// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/hmoragrega/paybile/service"
	mock "github.com/stretchr/testify/mock"
)

// TransferCreator is an autogenerated mock type for the TransferCreator type
type TransferCreator struct {
	mock.Mock
}

// CreateTransfer provides a mock function with given fields: ctx, req
func (_m *TransferCreator) CreateTransfer(ctx context.Context, req service.TransferRequest) (service.Transfer, error) {
	ret := _m.Called(ctx, req)

	var r0 service.Transfer
	if rf, ok := ret.Get(0).(func(context.Context, service.TransferRequest) service.Transfer); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(service.Transfer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, service.TransferRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
