// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/hmoragrega/paybile/service"
	mock "github.com/stretchr/testify/mock"
)

// UserReader is an autogenerated mock type for the UserReader type
type UserReader struct {
	mock.Mock
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *UserReader) GetByLogin(ctx context.Context, login string) (service.User, error) {
	ret := _m.Called(ctx, login)

	var r0 service.User
	if rf, ok := ret.Get(0).(func(context.Context, string) service.User); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(service.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
