// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	service "github.com/hmoragrega/paybile/service"
	mock "github.com/stretchr/testify/mock"
)

// UserResource is an autogenerated mock type for the UserResource type
type UserResource struct {
	mock.Mock
}

// IsOwner provides a mock function with given fields: user
func (_m *UserResource) IsOwner(user service.User) bool {
	ret := _m.Called(user)

	var r0 bool
	if rf, ok := ret.Get(0).(func(service.User) bool); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
