// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/hmoragrega/paybile/service"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WalletReader is an autogenerated mock type for the WalletReader type
type WalletReader struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, walletID
func (_m *WalletReader) GetByID(ctx context.Context, walletID uuid.UUID) (service.Wallet, error) {
	ret := _m.Called(ctx, walletID)

	var r0 service.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) service.Wallet); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Get(0).(service.Wallet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
