version: '3'

services:
  db:
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432

  api:
    build:
      dockerfile: cmd/service/Dockerfile
      context: ../../
    entrypoint: ["/bin/bash", "-c", "./api -db-dsn postgresql://paybile:paybilepw@db:5432/paybile?sslmode=disable"]
    ports:
      - 8080:8080

  migrator:
    build:
      dockerfile: cmd/migrator/Dockerfile
      context: ../../
    entrypoint: ["/bin/bash", "-c", "./migrator -direction up -db-dsn postgresql://paybile:paybilepw@db:5432/paybile?sslmode=disable"]
