// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "github.com/hmoragrega/paybile/service"

	uuid "github.com/google/uuid"
)

// TransactionLister is an autogenerated mock type for the TransactionLister type
type TransactionLister struct {
	mock.Mock
}

// ListTransactions provides a mock function with given fields: ctx, user, walletID, opt
func (_m *TransactionLister) ListTransactions(ctx context.Context, user service.User, walletID uuid.UUID, opt service.ListOptions) (service.TransactionList, error) {
	ret := _m.Called(ctx, user, walletID, opt)

	var r0 service.TransactionList
	if rf, ok := ret.Get(0).(func(context.Context, service.User, uuid.UUID, service.ListOptions) service.TransactionList); ok {
		r0 = rf(ctx, user, walletID, opt)
	} else {
		r0 = ret.Get(0).(service.TransactionList)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, service.User, uuid.UUID, service.ListOptions) error); ok {
		r1 = rf(ctx, user, walletID, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
